resolver: lts-12.10

packages:
- '.'
- location:
    git: https://github.com/jwaldmann/haskell_cudd
    commit: df01e5f6aba0a84c6a162ff56f1835d8998e12bf
  extra-dep: True
  
flags: {}

extra-package-dbs: []
